version: '3.8'

services:
  db:
    image: postgres:13
    container_name: hw02_bd
    restart: always
    environment:
       POSTGRES_USER: postgres
       POSTGRES_PASSWORD: 567234
       POSTGRES_db: hw02_bd
    ports:
      - "5432:5433"
    volumes:
      - pgdata:/var/lib/postgresql/data


  web:
    build: .
    container_name: hw02_web
    restart: always
    depends_on:
      - db
    environment:
      SQLALCHEMY_DATABASE_URL: postgresql+psycopyg2://postgres:567234@db5432/hw02_bd
    ports:
      - "80:8000"
    volumes:
      - .:/app

volumes:
  pgdata:


